version: '3'

vars:
  VERSION: "1.0.0"
  PORT: "8080"
  IMAGE_NAME: "terraform-mcp-server"
  CONTAINER_NAME: "terraform-mcp-server"

tasks:
  dockerBuild:
    cmds:
      - |
        docker build \
          --build-arg VERSION={{.VERSION}} \
          --build-arg PORT={{.PORT}} \
          -t {{.IMAGE_NAME}}:{{.VERSION}} .
  dockerRun:
    cmds:
      - |
        docker start "{{.CONTAINER_NAME}}" 2>/dev/null || \
        docker run --rm -d --name "{{.CONTAINER_NAME}}" -p {{.PORT}}:{{.PORT}} {{.IMAGE_NAME}}:{{.VERSION}} http

  test:
    cmds:
      - go test -v ./...
